INSERT INTO tb_game_list (nome) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (nome) VALUES ('Jogos de plataforma');

INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Mass Effect Trilogy', 2012, 'Role-playing (RPG), Shooter', 'XBox , Playstation , PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 4.8, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Red Dead Redemption 2', 2018, 'Role-playing (RPG), Adventure', 'XBox , Playstation , PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 4.7, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('The Witcher 3: Wild Hunt', 2014, 'Role-playing (RPG), Adventure', 'XBox , Playstation , PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 4.7, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Sekiro: Shadows Die Twice', 2019, 'Role-playing (RPG), Adventure', 'XBox , Playstation , PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 3.8, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Ghost of Tsushima', 2012, 'Role-playing (RPG), Adventure', 'XBox , Playstation , PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 4.6, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Super Mario World', 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 4.7, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Hollow Knight', 2017, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 4.6, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Ori and the Blind Forest', 2015, 'Plataforma', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 4, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Cuphead', 2017, 'Plataforma', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 4.6, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_games ( titulo, ano, genero, plataforma, img_url, nivel, descricao_curta, descricao_longa) VALUES ('Sonic CD', 1993, 'Plataforma', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 4, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');



INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (1, 1, 0);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (1, 2, 1);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (1, 3, 2);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (1, 4, 3);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (1, 5, 4);

INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (2, 6, 0);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (2, 7, 1);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (2, 8, 2);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (2, 9, 3);
INSERT INTO tb_posicao (list_id, game_id, posicao) VALUES (2, 10, 4);



